[package]
name = "boltwarden"
version = "1.0.0-rc.1"
edition = "2024"
rust-version = "1.95"
license-file = "LICENSE"
default-run = "boltwarden"

[dependencies]
eframe = { version = "0.36", default-features = false, features = ["accesskit", "default_fonts"] }
egui = "0.36"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
base64 = "0.23"
zeroize = "1"
subtle = "2"
signature = "3"
pbkdf2 = "0.13"
sha2 = "0.11"
uuid = { version = "1", features = ["v4"] }
aes = "0.9"
cbc = { version = "0.2", features = ["alloc"] }
hmac = "0.13"
hkdf = "0.13"
tokio = { version = "1", features = ["rt", "time", "macros"] }
futures-lite = "2"
sha1 = "0.11"
data-encoding = "2"
url = "2"
toml = "1"
image = { version = "0.25", default-features = false, features = ["png", "ico", "jpeg", "gif", "webp", "bmp"] }
resvg = { version = "0.48", default-features = false }
argon2 = "0.6"
ssh-key = { version = "0.7.0-rc.10", features = ["ed25519", "encryption", "p256", "p384", "p521"] }
zxcvbn = { version = "3.1", default-features = false }
p256 = { version = "0.14", features = ["ecdsa", "pkcs8"] }
psl = "2"
regex = "1"

getrandom = "0.4"

[target.'cfg(target_os = "linux")'.dependencies]
eframe = { version = "0.36", default-features = false, features = ["glow", "wayland", "x11"] }
libc = "0.2"
zbus = { version = "5.19", default-features = false, features = ["blocking-api", "tokio"] }
ksni = { version = "0.3", features = ["blocking"] }

[target.'cfg(target_os = "macos")'.dependencies]
eframe = { version = "0.36", default-features = false, features = ["wgpu_no_default_features"] }
wgpu = { version = "30.0", default-features = false, features = ["metal", "std", "wgsl"] }
libc = "0.2"

[target.'cfg(windows)'.dependencies]
eframe = { version = "0.36", default-features = false, features = ["wgpu_no_default_features"] }
wgpu = { version = "30.0", default-features = false, features = ["dx12", "std", "wgsl"] }
tray-icon = { version = "0.26", default-features = false }
windows-sys = { version = "0.61", features = [
    "Win32_Foundation", "Win32_Security", "Win32_Security_Authorization",
    "Win32_Storage_FileSystem", "Win32_System_IO", "Win32_System_Pipes",
    "Win32_System_Threading", "Win32_System_Memory", "Win32_System_Registry",
    "Win32_System_DataExchange", "Win32_System_RemoteDesktop",
    "Win32_System_SystemInformation", "Win32_System_Time", "Win32_System_LibraryLoader",
    "Win32_System_Diagnostics_ToolHelp", "Win32_System_Console",
    "Win32_UI_WindowsAndMessaging", "Win32_UI_Shell", "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Graphics_Gdi", "Win32_System_Com"
] }

[build-dependencies]
embed-resource = "3.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
